stages:
  - deploy

Git MIRROR:
  stage: deploy
  script:
    - ls -la
    - git fetch --all
    - git push https://$GITHUB_DEPLOY_USER:$GITHUB_DEPLOY_PASSWORD@github.com/vertigobr/docker-base.git master

